version: '3.2'

services:
  cadvisor:
    deploy:
      endpoint_mode: dnsrr
      mode: global
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run:/var/run:rw

  docker-exporter:
    build:
      context: ./docker/docker-exporter
      dockerfile: ./Dockerfile
    deploy:
      endpoint_mode: dnsrr
      mode: global

  node-exporter:
    command:
      - -collector.procfs
      - /host/proc
      - -collector.sysfs
      - /host/sys
      - -collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc)($$|/)
    deploy:
      endpoint_mode: dnsrr
      mode: global
    image: quay.io/prometheus/node-exporter
    volumes:
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

  prometheus:
    build:
      context: ./docker/prometheus
      dockerfile: ./Dockerfile
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
